#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id:
#            client-secret:
#            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
#            authorization-grant-type: authorization_code
#            scope: email