server:
  port: 8080
spring:
  profiles:
    active: local
#    include: oauth2
  datasource:
    url: jdbc:mariadb://localhost:3306/project_base
    username: jsy
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret:
    key: testSecretKey20230327testSecretKey20230327testSecretKey20230327